{application,security,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{security_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,['Elixir.Security.Application','Elixir.Security',
                        broadcast,code_lock,display,security_app,
                        security_sup]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
