---
name: Integration

on: push

env:
  ELIXIR_VERSION: 1.13.3
  OTP_VERSION: 23.2.3

jobs:
  test:
    runs-on: ubuntu-latest
    name: master
    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{env.OTP_VERSION}}
          elixir-version: ${{env.ELIXIR_VERSION}}

      - name: Cache Build Directory for the Current OTP/ELIXIR versions
        uses: actions/cache@v2
        id: cache-build
        with:
          path: _build
          key: build-test-elixir${{ env.ELIXIR_VERSION }}-otp-${{ env.OTP_VERSION }}
          restore-keys: |
            build-test-elixir${{ env.ELIXIR_VERSION }}-otp-${{ env.OTP_VERSION }}

      - name: "Get dependencies"
        run: mix deps.get

      - name: Cache Dependencies
        uses: actions/cache@v2
        id: cache-deps
        with:
          path: deps
          key: deps-${{ env.MIX_ENV }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-${{ env.MIX_ENV }}-${{ hashFiles('**/mix.lock') }}

      - name: "Get dependencies"
        run: mix deps.get

      - name: Check Unused Dependencies
        run: mix deps.unlock --check-unused

      - name: Compile the Project
        run: mix compile --warnings-as-errors

#      - name: Check Elixir Code Format
#        run: mix format --check-formatted

      - name: Run Elixir Tests
        run: mix test --trace --warnings-as-errors

      - name: "Dialyzer"
        run: MIX_ENV=dev mix dialyzer